### ISSUE TITLE
Save secrets as text files

### ISSUE THREAD

**Issue by BalmungSan** [CircleCI-Public/aws-parameter-store-orb#11]
## What would you like to be added

We have some secrets that we need as text files to be further processed by other tools.  
As of today, we are doing this:

```bash
aws ssm get-parameters --names 'name' --with-decryption --query 'Parameters[0].{_:Value}' --output text > file.txt
```

## Why is this needed

Of course, we could just `echo $ENV_VAR > file.txt`, but IMHO, then we are better just using the cli.
However, we still think this could be a useful feature for this orb. It could even include options for specifying a custom query and change the output type between text and json.

**Comment by KyleTryon** [comment]
Hello @BalmungSan,

I hear what you are saying. In this case, I agree that I believe it may be better to use the CLI directly in some cases rather than the user needing to learn the "new" syntax of the orb YAML when the code needed is very short. 

Sorry we took so long to respond to you. If you are still interested we would be open to a PR for this issue. For now, we will close this issue. Thank you.
